# Generated by Django 4.2.17 on 2025-05-28 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=12, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('balance', models.PositiveBigIntegerField(verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.documentmodel', verbose_name='Документ')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.organizationmodel', verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
                'db_table': 'payments',
            },
        ),
    ]
