# Generated by Django 4.2.17 on 2025-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='inn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ИНН'),
        ),
    ]
