# Generated by Django 4.2.17 on 2025-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_organizationmodel_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='inn',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ИНН'),
        ),
    ]
