# Generated by Django 4.2.17 on 2025-05-29 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_organizationmodel_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='balance',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='inn',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ИНН'),
        ),
    ]
