# Generated by Django 4.2.17 on 2025-05-29 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_organizationmodel_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='number',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='inn',
            field=models.PositiveBigIntegerField(db_index=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ИНН'),
        ),
    ]
