version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    networks:
      - test_payment_service_network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  app:
    build: ..
    env_file:
      - .env
    container_name: app
    networks:
      - test_payment_service_network
    command: bash -c "python manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - mysql
    restart: on-failure:10

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "8090:8000"
    expose:
      - 8090
    networks:
      - test_payment_service_network
    depends_on:
      - app
    container_name: app_nginx

networks:
  test_payment_service_network: {}

volumes:
  mysql_data:
  static_data: {}