from enum import Enum


class TransactionLevel(str, Enum):
    READ_UNCOMMITTED = 'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED'
    READ_COMMITTED = 'SET TRANSACTION ISOLATION LEVEL READ COMMITTED'
    REPEATABLE_READ = 'SET TRANSACTION ISOLATION LEVEL REPEATABLE READ'
    SERIALIZABLE = 'SET TRANSACTION ISOLATION LEVEL SERIALIZABLE'
